http_port: "3128"
http_intercept_port: "3130"
https_intercept_port: "3131"
certificate_dir: "/etc/squid3/ssl_cert"
certfile: "cert.pem"
keyfile: "key.pem"
csrfile: "csr.der"
proxy_user: "proxy"
acl_dir: "/etc/squid3/acls"
sslcrtd_program: "/usr/lib/squid3/ssl_crtd"
coredump_dir: "/var/spool/squid"
ssl_db_dir: "/var/lib/ssl_db"
squid_conf_dir: "/etc/squid3"
squid_log_dir: "/var/log/squid3"
squid_lib_dir: "/usr/lib/squid3"
icap_reqmod_url: "icap://127.0.0.1:13440/archangel"
icap_respmod_url: "icap://127.0.0.1:13440/archangel"
dns_nameservers: "127.0.0.1"
local_net: "192.168.1.0/24"

# Change these as you wish
country: "US"
state: "TX"
location: "Austin"
org: "ArchAngel"
org_unit: "SSLProxy"
cn: "ArchAngelFilter"